### ISSUE TITLE
დაჭრისას წყვეტილი ასოების გათვალისწინება

### ISSUE THREAD

**Issue by rimnadze** [m-learning/georgian-ocr-v2#10]
!-ს ვერ ცნობს

**Comment by sosoxuc** [comment]
ასევე სურათიდან https://github.com/m-learning/georgian-ocr-v2/releases/download/v2.0.1/mnatobi.png
ვერ სცნობს "რ" ასოებს რადგან ტექსტში "რ"-ს ძირი და ზედა არ არის გადაბმული
და ჩვენი სისტემა აღიქვავს როგორც ცალ-ცალკე სიმბოლოებს და იცნობს როგორც "ო"-ს და "7"-ს
