### ISSUE TITLE
ocr ვებ-გვერდი

### ISSUE THREAD

**Issue by sosoxuc** [m-learning/georgian-ocr-v2#2]
გვჭირდება მარტივი ვებ-გვერდი
მომხმარებელი ატვირთავს jpg სურათს და უკან მიიღებს ტექსტს

**Comment by GeorgeGorelishvili** [comment]
აკეთებს ვინმე მაგ თასქს?

**Comment by sosoxuc** [comment]
ჯერ-ჯერობით არა როგორც ვიცი

**Comment by rimnadze** [comment]
ძალიან საბაზისოა, მაგრამ არის.
