### ISSUE TITLE
საიტზე პარალელური მოთხოვნები არ კეთდება

### ISSUE THREAD

**Issue by rimnadze** [m-learning/georgian-ocr-v2#8]
ერთი და იგივე დირექტორიაზეა მიმართული სურათების დაგენერირება. მეორე მოთხოვნის გაშვება პირველის ფაილებს წაშლის.

**Comment by sosoxuc** [comment]
მემგონი ფაილების მაგივრად მეხსიერებასი შენახვაც იმუშავებს და ეს პრობლემა ავტომატურად მოიხსნება, მოსაფიქრებელია ჯამში

**Comment by sosoxuc** [comment]
გასწორდა

მადლობა @SaturnR
